export const FETCH_USER = 'fetch_user'
export const DEDUCT_CREDIT = 'deduct_credit'
export const ADD_COURSE = 'add_course'
export const ADD_COURSE_SUCCESS = 'add_course_success'
export const ADD_COURSE_ERROR = 'add_course_error'
export const FETCH_COURSE = 'fetch_course'
export const UNLOCK_COURSE = 'unlock_course'
export const UNLOCK_COURSE_SUCCESS = 'unlock_course_success'
export const UNLOCK_COURSE_ERROR = 'unlock_course_error'
export const FETCH_SINGLE_COURSE = "fetch_single_course"
export const FETCH_SINGLE_COURSE_SUCCESS = "fetch_single_course_success"
export const FETCH_SINGLE_COURSE_ERROR = "fetch_single_course_error"
export const ADD_TEACHER = "add_teacher"
export const ADD_TEACHER_SUCCESS = "add_teacher_success"
export const ADD_TEACHER_ERROR = "add_teacher_error"
export const FETCH_TEACHERS = "fetch_teachers"
export const LOGIN_USER = "login_user"
export const LOGIN_USER_SUCCESS = "login_user_success"
export const LOGIN_USER_ERROR = "login_user_error"
export const EDIT_COURSE ="edit_course"
export const EDIT_COURSE_SUCCESS ="edit_course_success"
export const EDIT_COURSE_ERROR ="edit_course_error"
export const UPDATE_COURSE = "update_course"
export const UPDATE_COURSE_SUCCESS = "update_course_success"
export const UPDATE_COURSE_ERROR = "update_course_error"
export const DELETE_COURSE = "delete_course"
export const DELETE_COURSE_SUCCESS = "delete_course_success"
export const DELETE_COURSE_ERROR = "delete_course_error"
export const CLEAR_DATA = "clear_data"
export const SEARCH_COURSE = "search_course"
export const SEARCH_COURSE_SUCCESS = "search_course_success"
export const SEARCH_COURSE_ERROR = "search_course_error"
export const FETCH_TEACHER_COURSE = "fetch_teacher_course"
export const FETCH_TEACHER_COURSE_SUCCESS = "fetch_teacher_course_success"
export const FETCH_TEACHER_COURSE_ERROR = "fetch_teacher_course_error"
export const FETCH_USER_COURSE ="fetch_user_course"
export const FETCH_USER_COURSE_SUCCESS ="fetch_user_course_success"
export const FETCH_USER_COURSE_ERROR ="fetch_user_course_error"
export const FETCH_ALL_TEACHER = "fetch_all_teacher"
export const FETCH_ALL_STUDENT = "fetch_all_student"


